
import java.awt.event.KeyEvent;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author basil
 */
public class StudentMarksUI extends javax.swing.JFrame {
    
    
    
    
    /**
     * Creates new form StudentMarksUI
     */
    public StudentMarksUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        marksLabel = new javax.swing.JLabel();
        marksBox = new javax.swing.JTextField();
        ascendingMarksArea = new javax.swing.JScrollPane();
        ascendingMarksArea1 = new javax.swing.JTextArea();
        Enter = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Student Marks");

        marksLabel.setText("Enter Marks Here:");

        marksBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksBoxActionPerformed(evt);
            }
        });
        marksBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                marksBoxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                marksBoxKeyTyped(evt);
            }
        });

        ascendingMarksArea1.setColumns(20);
        ascendingMarksArea1.setRows(5);
        ascendingMarksArea.setViewportView(ascendingMarksArea1);

        Enter.setText("Enter");
        Enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(0, 208, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(marksLabel)
                        .addGap(18, 18, 18)
                        .addComponent(marksBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Enter))
                    .addComponent(ascendingMarksArea, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marksLabel)
                    .addComponent(marksBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Enter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ascendingMarksArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marksBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marksBoxActionPerformed

    private void marksBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marksBoxKeyTyped
        
    }//GEN-LAST:event_marksBoxKeyTyped

    private void EnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterMouseClicked
        
        markListUnsorted.add(Integer.parseInt(marksBox.getText()));
            
            marksBox.setText("");
    }//GEN-LAST:event_EnterMouseClicked

    private void marksBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marksBoxKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            markListUnsorted.add(Integer.parseInt(marksBox.getText()));
            
            marksBox.setText("");
        }
    }//GEN-LAST:event_marksBoxKeyPressed

    public void main(String args[]) {
    
    ArrayList<Integer> markListUnsorted = new ArrayList();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMarksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMarksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMarksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMarksUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMarksUI().setVisible(true);
            }
        });
        
        
        
        for(int a = 0; a < markListUnsorted.size(); a++) {
            
            ascendingMarksArea1.setText(ascendingMarksArea1.getText() + Integer.toString(markListUnsorted.get(a)));
        }
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enter;
    private javax.swing.JScrollPane ascendingMarksArea;
    private javax.swing.JTextArea ascendingMarksArea1;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField marksBox;
    private javax.swing.JLabel marksLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
